"""add colour to thing

Revision ID: 20e61e1fff17
Revises: a7384b7d2aef
Create Date: 2021-07-07 23:12:22.909142

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20e61e1fff17"
down_revision = "a7384b7d2aef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("thing", sa.Column("colour", sa.String(), nullable=False))
    op.create_index(op.f("ix_thing_colour"), "thing", ["colour"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_thing_colour"), table_name="thing")
    op.drop_column("thing", "colour")
    # ### end Alembic commands ###
